In [4]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Take Home Assignment Dataset.csv")

In [3]:
df.head(20)

,Route Number,Date of Extraction,Departure Date,SRP Rank,Operator,Bus Type,Is AC,Is Seater,Is Sleeper,Departure Time,...,Available Upper Seats,Available Lower Seats,BP Count,DP Count,Total Ratings,Number of Reviews,Bus Score,Is Seat Layout Available,Is Live Tracking Available,Is M-Ticket Enabled
0,Route 1,"16 Mar 2026, 09:34:45",16-Mar,1/165,Operator 1,Electric A/C Seater (2+2),True,True,NaN,17:50,...,NaN,41.0,12,14,4.6,459.0,3.71,True,True,True
1,Route 1,"16 Mar 2026, 09:34:45",16-Mar,2/165,Operator 2,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:00,...,14.0,12.0,13,20,4.9,408.0,4.48,True,True,True
2,Route 1,"16 Mar 2026, 09:34:45",16-Mar,3/165,Operator 3,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:15,...,11.0,9.0,12,30,4.8,173.0,3.77,True,True,True
3,Route 1,"16 Mar 2026, 09:34:45",16-Mar,4/165,Operator 3,A/C Sleeper (2+1),True,NaN,True,23:15,...,11.0,12.0,31,28,4.6,781.0,3.91,True,True,True
4,Route 1,"16 Mar 2026, 09:34:45",16-Mar,5/165,Operator 4,Bharat Benz A/C Sleeper (2+1),True,NaN,True,23:40,...,10.0,11.0,12,23,4.7,320.0,3.80,True,True,True
5,Route 1,"16 Mar 2026, 09:34:45",16-Mar,6/165,Operator 2,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:30,...,11.0,13.0,13,23,4.9,1089.0,5.00,True,True,True
6,Route 1,"16 Mar 2026, 09:34:45",16-Mar,7/165,Operator 5,A/C Sleeper (2+1),True,NaN,True,23:30,...,13.0,12.0,14,7,4.8,1188.0,4.69,True,True,True
7,Route 1,"16 Mar 2026, 09:34:45",16-Mar,8/165,Operator 6,A/C Seater/Sleeper (2+1),True,True,True,22:45,...,8.0,21.0,5,17,4.8,1019.0,4.62,True,True,True
8,Route 1,"16 Mar 2026, 09:34:45",16-Mar,9/165,Operator 7,AC Sleeper (2+1),True,NaN,True,23:20,...,15.0,11.0,28,22,4.1,617.0,2.84,True,True,True
9,Route 1,"16 Mar 2026, 09:34:45",16-Mar,10/165,Operator 8,Bharat Benz A/C Sleeper (2+1),True,NaN,True,23:00,...,8.0,8.0,26,30,4.8,881.0,4.55,True,True,True
10,Route 1,"16 Mar 2026, 09:34:45",16-Mar,11/165,Operator 1,Electric A/C Seater (2+2),True,True,NaN,17:50,...,NaN,41.0,12,14,4.6,459.0,3.71,True,True,True
11,Route 1,"16 Mar 2026, 09:34:45",16-Mar,12/165,Operator 8,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:30,...,11.0,9.0,26,32,4.8,807.0,4.50,True,True,True
12,Route 1,"16 Mar 2026, 09:34:45",16-Mar,13/165,Operator 9,A/C Sleeper (2+1),True,NaN,True,22:05,...,12.0,11.0,18,24,4.7,312.0,3.79,True,True,True
13,Route 1,"16 Mar 2026, 09:34:45",16-Mar,14/165,Operator 10,A/C Seater / Sleeper (2+1),True,True,True,22:00,...,10.0,7.0,5,19,4.8,786.0,4.49,True,True,True
14,Route 1,"16 Mar 2026, 09:34:45",16-Mar,15/165,Operator 2,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:00,...,14.0,12.0,13,20,4.9,408.0,4.48,True,True,True
15,Route 1,"16 Mar 2026, 09:34:45",16-Mar,16/165,Operator 3,Bharat Benz A/C Sleeper (2+1),True,NaN,True,22:15,...,11.0,9.0,12,30,4.8,173.0,3.77,True,True,True
16,Route 1,"16 Mar 2026, 09:34:45",16-Mar,17/165,Flixbus,A/C Sleeper (2+1),True,NaN,True,22:50,...,5.0,9.0,20,22,4.7,992.0,4.29,True,True,True
17,Route 1,"16 Mar 2026, 09:34:45",16-Mar,18/165,Operator 6,A/C Seater / Sleeper (2+1),True,True,True,21:45,...,11.0,17.0,5,17,4.9,258.0,4.24,True,True,True
18,Route 1,"16 Mar 2026, 09:34:45",16-Mar,19/165,Operator 7,A/C Seater / Sleeper (2+1),True,True,True,22:10,...,13.0,11.0,16,15,4.6,1251.0,4.10,True,True,True
19,Route 1,"16 Mar 2026, 09:34:45",16-Mar,20/165,Operator 1,Electric A/C Seater/Sleeper (2+1),True,True,True,19:10,...,15.0,23.0,12,12,4.7,642.0,4.10,True,True,True

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 862388 entries, 0 to 862387
Data columns (total 32 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Route Number                862388 non-null  str
 1   Date of Extraction          862388 non-null  str
 2   Departure Date              862388 non-null  str
 3   SRP Rank                    862388 non-null  str
 4   Operator                    862388 non-null  str
 5   Bus Type                    862388 non-null  str
 6   Is AC                       783656 non-null  object
 7   Is Seater                   404276 non-null  object
 8   Is Sleeper                  746178 non-null  object
 9   Departure Time              862388 non-null  str
 10  Arrival Time                862388 non-null  str
 11  Journey Duration (Min)      862388 non-null  int64
 12  DOJ                         862388 non-null  str
 13  Fare List                   862388 non-null  str
 14  Discounted Prices           273302 non-null  str
 15  Weighted Average Price      861633 non-null  float64
 16  Seat Prices                 860881 non-null  str
 17  Available Seats             862388 non-null  int64
 18  Total Seats                 862388 non-null  int64
 19  Available Window Seats      841170 non-null  float64
 20  Available Single Seats      716090 non-null  float64
 21  Available Aisle Seats       841497 non-null  float64
 22  Available Upper Seats       727920 non-null  float64
 23  Available Lower Seats       860976 non-null  float64
 24  BP Count                    862388 non-null  int64
 25  DP Count                    862388 non-null  int64
 26  Total Ratings               862388 non-null  float64
 27  Number of Reviews           849728 non-null  float64
 28  Bus Score                   855675 non-null  float64
 29  Is Seat Layout Available    862388 non-null  bool
 30  Is Live Tracking Available  622666 non-null  object
 31  Is M-Ticket Enabled         862388 non-null  bool
dtypes: bool(2), float64(9), int64(5), object(4), str(12)
memory usage: 199.0+ MB

In [8]:
df["Departure Time"] = pd.to_datetime(df["Departure Time"], format="%H:%M")
df["Arrival Time"] = pd.to_datetime(df["Arrival Time"], format="%H:%M")

In [9]:
bool_cols = ["Is AC","Is Seater","Is Sleeper","Is Live Tracking Available"]
df[bool_cols] = df[bool_cols].astype("boolean")

In [10]:
df["Route Number"] = df["Route Number"].astype("category")

In [11]:
df["Load_Factor"] = 1 - (df["Available Seats"] / df["Total Seats"])

In [12]:
df["Weighted Average Price"].isna().sum()

np.int64(755)

In [13]:
df = df.dropna(subset=["Weighted Average Price"])

In [14]:
df.columns = df.columns.str.replace(" ", "_")

In [15]:
df["Operator"].unique()[:20]

<StringArray>
[ 'Operator 1',  'Operator 2',  'Operator 3',  'Operator 4',  'Operator 5',
  'Operator 6',  'Operator 7',  'Operator 8',  'Operator 9', 'Operator 10',
     'Flixbus', 'Operator 12', 'Operator 13', 'Operator 14', 'Operator 15',
 'Operator 16', 'Operator 17', 'Operator 18', 'Operator 19', 'Operator 20']
Length: 20, dtype: str

In [6]:
df.describe()

,Journey Duration (Min),Weighted Average Price,Available Seats,Total Seats,Available Window Seats,Available Single Seats,Available Aisle Seats,Available Upper Seats,Available Lower Seats,BP Count,DP Count,Total Ratings,Number of Reviews,Bus Score
count,862388.000000,861633.000000,862388.000000,862388.000000,841170.000000,716090.000000,841497.000000,727920.000000,860976.000000,862388.000000,862388.000000,862388.000000,849728.000000,855675.000000
mean,543.696615,1721.756715,33.246885,40.757306,18.627534,9.566703,12.236734,14.660784,20.905246,11.789982,9.105799,3.788883,188.296197,1.585956
std,215.098523,1063.726904,8.291146,6.211717,4.747368,2.599130,4.033180,3.260792,9.460734,12.875211,8.776230,0.977090,240.251245,6.193369
min,-1165.000000,100.000000,1.000000,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-1.000000,0.000000,-99.000000
25%,395.000000,1000.000000,28.000000,36.000000,15.000000,8.000000,10.000000,12.000000,15.000000,3.000000,2.000000,3.500000,8.000000,1.240000
50%,515.000000,1450.000000,33.000000,40.000000,18.000000,10.000000,12.000000,15.000000,18.000000,7.000000,6.000000,4.100000,68.000000,1.730000
75%,675.000000,2081.500000,38.000000,46.000000,22.000000,12.000000,14.000000,17.000000,26.000000,17.000000,15.000000,4.400000,324.000000,2.840000
max,45390.000000,30843.540000,72.000000,72.000000,38.000000,33.000000,36.000000,27.000000,72.000000,96.000000,63.000000,5.000000,1909.000000,7.860000

In [17]:
important_cols = [
"Route_Number",
"Operator",
"Bus_Type",
"Departure_Time",
"Journey_Duration_(Min)",
"Weighted_Average_Price",
"Bus_Score",
"Number_of_Reviews",
"Available_Seats",
"Total_Seats"
]

df[important_cols].isnull().sum()

Route_Number                  0
Operator                      0
Bus_Type                      0
Departure_Time                0
Journey_Duration_(Min)        0
Weighted_Average_Price        0
Bus_Score                  6713
Number_of_Reviews         12658
Available_Seats               0
Total_Seats                   0
dtype: int64

In [18]:
df = df.dropna(subset=["Weighted_Average_Price"])

In [19]:
df["Number_of_Reviews"] = df["Number_of_Reviews"].fillna(0)

In [20]:
df["Bus_Score"] = df["Bus_Score"].fillna(df["Bus_Score"].mean())

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.shape

(861633, 33)

In [25]:
df["dep_minutes"] = df["Departure_Time"].dt.hour * 60 + df["Departure_Time"].dt.minute

In [26]:
flix = df[df["Operator"] == "Flixbus"].copy()
others = df[df["Operator"] != "Flixbus"].copy()

In [27]:
len(flix), len(others)

(31090, 830543)

In [31]:
test_bus = flix.iloc[0]
test_bus

Route_Number                                                            Route 1
Date_of_Extraction                                        16 Mar 2026, 09:34:45
Departure_Date                                                           16-Mar
SRP_Rank                                                                 17/165
Operator                                                                Flixbus
Bus_Type                                                      A/C Sleeper (2+1)
Is_AC                                                                      True
Is_Seater                                                                  <NA>
Is_Sleeper                                                                 True
Departure_Time                                              1900-01-01 22:50:00
Arrival_Time                                                1900-01-01 05:50:00
Journey_Duration_(Min)                                                      420
DOJ                                                                  16-03-2026
Fare_List                     562.71-583.9-668.64-710.17-711.02-753.39-964.4...
Discounted_Prices                                                           NaN
Weighted_Average_Price                                                   795.39
Seat_Prices                   562.71:2,583.9:2,668.64:2,710.17:1,711.02:1,75...
Available_Seats                                                              14
Total_Seats                                                                  36
Available_Window_Seats                                                      7.0
Available_Single_Seats                                                      6.0
Available_Aisle_Seats                                                       6.0
Available_Upper_Seats                                                       5.0
Available_Lower_Seats                                                       9.0
BP_Count                                                                     20
DP_Count                                                                     22
Total_Ratings                                                               4.7
Number_of_Reviews                                                         992.0
Bus_Score                                                                  4.29
Is_Seat_Layout_Available                                                   True
Is_Live_Tracking_Available                                                 True
Is_M-Ticket_Enabled                                                        True
Load_Factor                                                            0.611111
dep_minutes                                                                1370
Name: 16, dtype: object

In [38]:
route = test_bus["Route_Number"]
bus_type = test_bus["Bus_Type"]
dep_time = test_bus["dep_minutes"]
duration = test_bus["Journey_Duration_(Min)"]
price = test_bus["Weighted_Average_Price"]
date = test_bus["Departure_Date"]

In [48]:
similar = others[
    (others["Route_Number"] == route) &
    (others["Bus_Type"] == bus_type) &
    (others["Departure_Date"] == date) &
    (abs(others["dep_minutes"] - dep_time) <= 60) &
    (abs(others["Journey_Duration_(Min)"] - duration) <= 30)
]

In [33]:
similar[["Operator","Weighted_Average_Price","Departure_Time"]].head()

       Operator  Weighted_Average_Price      Departure_Time
6    Operator 5                 1004.00 1900-01-01 23:30:00
12   Operator 9                 1018.56 1900-01-01 22:05:00
23  Operator 13                  922.72 1900-01-01 21:50:00
37  Operator 12                  802.50 1900-01-01 23:00:00
45  Operator 23                  852.00 1900-01-01 22:00:00

In [49]:
len(similar)

54

In [50]:
market_price = similar["Weighted_Average_Price"].mean()
market_price

np.float64(1085.2474074074073)

In [51]:
price_difference = price - market_price
price_difference

np.float64(-289.8574074074073)

In [52]:
if price > market_price * 1.2:
    flag = "Overpriced"
elif price < market_price * 0.8:
    flag = "Underpriced"
else:
    flag = "OK"

flag

'Underpriced'

In [53]:
print("Flixbus price:", price)
print("Market price:", market_price)
print("Difference:", price_difference)
print("Flag:", flag)

Flixbus price: 795.39
Market price: 1085.2474074074073
Difference: -289.8574074074073
Flag: Underpriced

In [54]:
results = []

In [55]:
for idx, bus in flix.iterrows():

    route = bus["Route_Number"]
    bus_type = bus["Bus_Type"]
    dep_time = bus["dep_minutes"]
    duration = bus["Journey_Duration_(Min)"]
    date = bus["Departure_Date"]
    price = bus["Weighted_Average_Price"]

    similar = others[
        (others["Route_Number"] == route) &
        (others["Bus_Type"] == bus_type) &
        (others["Departure_Date"] == date) &
        (abs(others["dep_minutes"] - dep_time) <= 60) &
        (abs(others["Journey_Duration_(Min)"] - duration) <= 30)
    ]

    if len(similar) == 0:
        continue

    market_price = similar["Weighted_Average_Price"].mean()
    price_diff = price - market_price

    if price > market_price * 1.2:
        flag = "Overpriced"
    elif price < market_price * 0.8:
        flag = "Underpriced"
    else:
        flag = "OK"

    results.append({
        "Route": route,
        "Date": date,
        "Flixbus_Price": price,
        "Market_Price": market_price,
        "Price_Difference": price_diff,
        "Flag": flag,
        "Competitors_Compared": len(similar)
    })

KeyboardInterrupt:

In [57]:
groups = df.groupby(["Route_Number","Bus_Type","Departure_Date"])

In [58]:
results = []

for (route, bus_type, date), group in groups:

    flix_group = group[group["Operator"] == "Flixbus"]
    others_group = group[group["Operator"] != "Flixbus"]

    if len(flix_group) == 0 or len(others_group) == 0:
        continue

    for _, bus in flix_group.iterrows():

        dep_time = bus["dep_minutes"]
        duration = bus["Journey_Duration_(Min)"]
        price = bus["Weighted_Average_Price"]

        similar = others_group[
            (abs(others_group["dep_minutes"] - dep_time) <= 60) &
            (abs(others_group["Journey_Duration_(Min)"] - duration) <= 30)
        ]

        if len(similar) == 0:
            continue

        market_price = similar["Weighted_Average_Price"].mean()
        diff = price - market_price

        if price > market_price * 1.2:
            flag = "Overpriced"
        elif price < market_price * 0.8:
            flag = "Underpriced"
        else:
            flag = "OK"

        results.append({
            "Route": route,
            "Date": date,
            "Flixbus_Price": price,
            "Market_Price": market_price,
            "Price_Difference": diff,
            "Flag": flag,
            "Competitors_Compared": len(similar)
        })

In [59]:
results_df = pd.DataFrame(results)

In [60]:
results_df.shape

(17335, 7)

In [61]:
results_df["Flag"].value_counts()

Flag
Underpriced    8778
OK             6104
Overpriced     2453
Name: count, dtype: int64

In [62]:
results_df.head()

,Route,Date,Flixbus_Price,Market_Price,Price_Difference,Flag,Competitors_Compared
0,Route 1,01-Apr,1510.13,1179.121667,331.008333,Overpriced,24
1,Route 1,01-Apr,1964.37,1179.121667,785.248333,Overpriced,24
2,Route 1,02-Apr,1510.13,1327.232727,182.897273,OK,22
3,Route 1,02-Apr,1964.37,1327.232727,637.137273,Overpriced,22
4,Route 1,03-Apr,1510.13,1270.461538,239.668462,OK,13

In [63]:
results_df.to_excel("flixbus_price_flags.xlsx", index=False)

In [64]:
results_df["Price_Diff_%"] = (
    results_df["Price_Difference"] / results_df["Market_Price"]
) * 100

In [67]:
results_df.columns

Index(['Route', 'Date', 'Flixbus_Price', 'Market_Price', 'Price_Difference',
       'Flag', 'Competitors_Compared', 'Price_Diff_%'],
      dtype='str')

In [68]:
results_df = results_df.rename(columns={
    "Route":"Route_Number",
    "Date":"Departure_Date"
})

In [69]:
results_df["Market_Price"] = results_df["Market_Price"].round(2)
results_df["Price_Difference"] = results_df["Price_Difference"].round(2)
results_df["Price_Diff_%"] = results_df["Price_Diff_%"].round(2)

In [70]:
results_df = results_df.sort_values(by="Price_Diff_%", ascending=False)

In [71]:
results_df.to_excel("Flixbus_Pricing_Flags_Final.xlsx", index=False)